version: '3.8'

services:
  backend:
    build:
      context: ./Backend
    volumes:
      - ./Backend:/app
      - ./Backend/data:/app/data
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./Fronted
    volumes:
      - ./Fronted:/apli
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
